name: markdown_editor
description: A simple markdown editor, supports minimal features, possible future features coming
publish_to: none

version: 0.0.1+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

scripts: derry.yaml
