name: markdown_editor
description: A simple Markdown editor for Flutter that supports basic Markdown elements such as bold, headers, highlighting, italics, links, ordered lists, and unordered lists.
version: 0.1.0
homepage: https://github.com/mrgnhnt96/markdown_editor
repository: https://github.com/mrgnhnt96/markdown_editor
topics:
  - markdown
  - text_editor
  - rich_text
  - HTML
  - text_input_widget

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  derry: ^1.5.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

scripts: derry.yaml
